import React, { useState, type ChangeEvent } from 'react';
import { useNavigate } from 'react-router-dom';
import { Input, Button, Card, Modal } from '@dobara/ui';
import { setUser } from '../App';

/** APP-P0-05 — new-user second half: set password + confirm + agreement, then finish registration. */

const KNOWN_USERS_KEY = 'dobara_registered_phones';

export function isKnownUser(phone: string): boolean {
  try {
    const list = JSON.parse(localStorage.getItem(KNOWN_USERS_KEY) || '[]') as string[];
    return list.includes(phone);
  } catch {
    return false;
  }
}

export function markRegistered(phone: string) {
  try {
    const list = JSON.parse(localStorage.getItem(KNOWN_USERS_KEY) || '[]') as string[];
    if (!list.includes(phone)) {
      list.push(phone);
      localStorage.setItem(KNOWN_USERS_KEY, JSON.stringify(list));
    }
  } catch { /* ignore */ }
}

/** C-end password rule (APP-P0-05): 8–20 chars, ≥2 of upper/lower/digit/special. */
function passwordErrors(pw: string): string[] {
  const errs: string[] = [];
  if (pw.length < 8) errs.push('At least 8 characters');
  if (pw.length > 20) errs.push('At most 20 characters');
  const classes = [/[A-Z]/.test(pw), /[a-z]/.test(pw), /\d/.test(pw), /[!@#$%^&*()_+=\-[\]{};':",.<>/?\\|]/.test(pw)];
  if (classes.filter(Boolean).length < 2) errs.push('At least 2 character types (upper/lower/digit/special)');
  if (/(.)\1\1/.test(pw)) errs.push('No 3+ repeated characters (e.g. "aaa")');
  if (/(012|123|234|345|456|567|678|789|987|876|765|654|543|432|321|210)/.test(pw)) {
    errs.push('No 3+ sequential digits (e.g. "123")');
  }
  return errs;
}

function strengthOf(pw: string): { level: 0 | 1 | 2 | 3; label: string } {
  if (!pw) return { level: 0, label: '' };
  const classes = [/[A-Z]/.test(pw), /[a-z]/.test(pw), /\d/.test(pw), /[^A-Za-z0-9]/.test(pw)].filter(Boolean).length;
  if (classes >= 3) return { level: 3, label: 'Strong' };
  if (classes === 2) return { level: 2, label: 'Medium' };
  return { level: 1, label: 'Weak' };
}

const STRENGTH_COLORS = ['', 'bg-dobara-error', 'bg-dobara-warning', 'bg-dobara-success'];

/** Shared legal-doc modal body (login page bottom links + registration checkbox). */
export function LegalDoc({ doc, open, onClose }: { doc: 'agreement' | 'privacy' | null; open: boolean; onClose: () => void }) {
  return (
    <Modal
      open={open}
      onClose={onClose}
      title={doc === 'agreement' ? 'User Agreement' : 'Privacy Policy'}
      size="lg"
    >
      <div className="space-y-3 max-h-[60vh] overflow-y-auto text-caption text-text-secondary">
        {doc === 'agreement' ? (
          <>
            <p className="font-semibold text-text-primary">Dobara User Agreement (Demo)</p>
            <p>1. Dobara is a certified pre-owned device marketplace. By registering you agree to trade-in and purchase under these terms.</p>
            <p>2. Trade-in quotes are generated by our pricing engine based on on-site device inspection and are valid for 30 minutes.</p>
            <p>3. Purchased devices are covered by the 7-day after-sales policy for undisclosed quality issues.</p>
            <p>4. Accounts are identified by mobile number; you are responsible for keeping your credentials secure.</p>
            <p className="text-text-muted">Full legal text will be provided at production launch.</p>
          </>
        ) : (
          <>
            <p className="font-semibold text-text-primary">Dobara Privacy Policy (Demo)</p>
            <p>1. We collect your mobile number, name and addresses to provide trade-in, purchase and after-sales services.</p>
            <p>2. Device IMEIs collected during inspection are encrypted, de-duplicated and used only for pricing and listing.</p>
            <p>3. We use MSG91 to deliver OTP and transactional SMS; location (city-level) is used for same-city recommendations.</p>
            <p>4. You may request account deletion in Settings; a 30-day cooling-off period applies before permanent deletion.</p>
            <p className="text-text-muted">Full legal text will be provided at production launch.</p>
          </>
        )}
      </div>
    </Modal>
  );
}

export function Register({ phone }: { phone: string }) {
  const navigate = useNavigate();
  const [password, setPassword] = useState('');
  const [confirm, setConfirm] = useState('');
  const [agree, setAgree] = useState(false);
  const [error, setError] = useState('');
  const [docOpen, setDocOpen] = useState<'agreement' | 'privacy' | null>(null);
  const [submitting, setSubmitting] = useState(false);

  const errors = password ? passwordErrors(password) : [];
  const confirmMismatch = confirm.length > 0 && password !== confirm;
  const canSubmit = password.length > 0 && errors.length === 0 && password === confirm && agree && !submitting;

  const submit = async () => {
    if (!canSubmit) return;
    setSubmitting(true);
    try {
      await fetch('/api/auth/register', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ phone, password }),
      }).catch(() => { /* demo fallback below */ });
      markRegistered(phone);
      setUser(phone, 'Demo User');
      navigate('/home', { replace: true });
    } finally {
      setSubmitting(false);
    }
  };

  return (
    <div className="min-h-screen bg-surface flex items-center justify-center">
      <div className="w-full max-w-sm">
        <div className="text-center mb-8">
          <h1 className="text-h2 font-extrabold text-primary-500 tracking-tight">Set your password</h1>
          <p className="text-body text-text-muted mt-2">Finish creating your account for +91 {phone}</p>
        </div>

        <Card className="space-y-4" data-testid="register-card">
          <div>
            <Input
              label="Password"
              type="password"
              value={password}
              onChange={(e: ChangeEvent<HTMLInputElement>) => { setPassword(e.target.value); setError(''); }}
              placeholder="8–20 chars, 2+ character types"
              data-testid="register-password"
              error={errors[0]}
            />
            {/* Password strength indicator (APP-P0-05) */}
            {password && (
              <div className="flex items-center gap-2 mt-2" data-testid="password-strength">
                <div className="flex gap-1 flex-1">
                  {[1, 2, 3].map((i) => (
                    <div
                      key={i}
                      className={`h-1.5 flex-1 rounded-full transition-colors ${strengthOf(password).level >= i ? STRENGTH_COLORS[strengthOf(password).level] : 'bg-surface-high'}`}
                    />
                  ))}
                </div>
                <span className="text-caption text-text-muted w-14 text-right">{strengthOf(password).label}</span>
              </div>
            )}
            {errors.length > 1 && (
              <ul className="text-caption text-text-muted mt-1.5 space-y-0.5 list-disc list-inside" data-testid="password-rules">
                {errors.slice(1).map((e) => <li key={e}>{e}</li>)}
              </ul>
            )}
          </div>

          <Input
            label="Confirm Password"
            type="password"
            value={confirm}
            onChange={(e: ChangeEvent<HTMLInputElement>) => setConfirm(e.target.value)}
            placeholder="Re-enter password"
            error={confirmMismatch ? 'Passwords do not match' : undefined}
            data-testid="register-confirm"
          />

          <label className="flex items-start gap-2 text-caption text-text-secondary cursor-pointer" data-testid="register-agree">
            <input
              type="checkbox"
              checked={agree}
              onChange={(e) => setAgree(e.target.checked)}
              className="accent-primary-500 w-4 h-4 mt-0.5 shrink-0"
            />
            <span>
              I have read and agree to the{' '}
              <button type="button" className="text-primary-600 underline" onClick={() => setDocOpen('agreement')}>
                User Agreement
              </button>{' '}
              and{' '}
              <button type="button" className="text-primary-600 underline" onClick={() => setDocOpen('privacy')}>
                Privacy Policy
              </button>
              .
            </span>
          </label>

          {error && <p className="text-caption text-dobara-error" data-testid="register-error">{error}</p>}

          <Button
            onClick={submit}
            loading={submitting}
            disabled={!canSubmit}
            className="w-full"
            data-testid="complete-registration"
          >
            Complete Registration
          </Button>
          {!agree && (
            <p className="text-caption text-text-muted text-center">Agree to the terms to enable registration</p>
          )}
        </Card>

        <LegalDoc doc={docOpen} open={docOpen !== null} onClose={() => setDocOpen(null)} />
      </div>
    </div>
  );
}
