import React, { useEffect, useState, type ChangeEvent } from 'react';
import { useNavigate } from 'react-router-dom';
import { Input, Button, Card, Modal } from '@dobara/ui';
import { Building2 } from 'lucide-react';
import type { IEntBinding } from '@dobara/utils';
import { setUser } from '../App';

/** APP-P0-05 — new-user second half: set password + account type + agreement, then finish registration.
 *  v2.21: account type 个人/企业 — enterprise requires a store selection (search the admin
 *  pre-imported store profile; binding created on completion = ROLE-ENT, 06 §2.12.2). */

/** 预导入门店档案条目（GET /api/ent/stores） */
interface IEntStoreHit {
  id: string;
  code?: string;
  name: string;
  city: string;
  enterpriseName?: string;
  gstin?: string;
}

const KNOWN_USERS_KEY = 'dobara_registered_phones';

export function isKnownUser(phone: string): boolean {
  try {
    const list = JSON.parse(localStorage.getItem(KNOWN_USERS_KEY) || '[]') as string[];
    return list.includes(phone);
  } catch {
    return false;
  }
}

export function markRegistered(phone: string) {
  try {
    const list = JSON.parse(localStorage.getItem(KNOWN_USERS_KEY) || '[]') as string[];
    if (!list.includes(phone)) {
      list.push(phone);
      localStorage.setItem(KNOWN_USERS_KEY, JSON.stringify(list));
    }
  } catch { /* ignore */ }
}

/** C-end password rule (APP-P0-05): 8–20 chars, ≥2 of upper/lower/digit/special. */
function passwordErrors(pw: string): string[] {
  const errs: string[] = [];
  if (pw.length < 8) errs.push('At least 8 characters');
  if (pw.length > 20) errs.push('At most 20 characters');
  const classes = [/[A-Z]/.test(pw), /[a-z]/.test(pw), /\d/.test(pw), /[!@#$%^&*()_+=\-[\]{};':",.<>/?\\|]/.test(pw)];
  if (classes.filter(Boolean).length < 2) errs.push('At least 2 character types (upper/lower/digit/special)');
  if (/(.)\1\1/.test(pw)) errs.push('No 3+ repeated characters (e.g. "aaa")');
  if (/(012|123|234|345|456|567|678|789|987|876|765|654|543|432|321|210)/.test(pw)) {
    errs.push('No 3+ sequential digits (e.g. "123")');
  }
  return errs;
}

function strengthOf(pw: string): { level: 0 | 1 | 2 | 3; label: string } {
  if (!pw) return { level: 0, label: '' };
  const classes = [/[A-Z]/.test(pw), /[a-z]/.test(pw), /\d/.test(pw), /[^A-Za-z0-9]/.test(pw)].filter(Boolean).length;
  if (classes >= 3) return { level: 3, label: 'Strong' };
  if (classes === 2) return { level: 2, label: 'Medium' };
  return { level: 1, label: 'Weak' };
}

const STRENGTH_COLORS = ['', 'bg-dobara-error', 'bg-dobara-warning', 'bg-dobara-success'];

/** Shared legal-doc modal body (login page bottom links + registration checkbox). */
export function LegalDoc({ doc, open, onClose }: { doc: 'agreement' | 'privacy' | null; open: boolean; onClose: () => void }) {
  return (
    <Modal
      open={open}
      onClose={onClose}
      title={doc === 'agreement' ? 'User Agreement' : 'Privacy Policy'}
      size="lg"
    >
      <div className="space-y-3 max-h-[60vh] overflow-y-auto text-caption text-text-secondary">
        {doc === 'agreement' ? (
          <>
            <p className="font-semibold text-text-primary">Dobara User Agreement (Demo)</p>
            <p>1. Dobara is a certified pre-owned device marketplace. By registering you agree to trade-in and purchase under these terms.</p>
            <p>2. Trade-in quotes are generated by our pricing engine based on on-site device inspection and are valid for 30 minutes.</p>
            <p>3. Purchased devices are covered by the 7-day after-sales policy for undisclosed quality issues.</p>
            <p>4. Accounts are identified by mobile number; you are responsible for keeping your credentials secure.</p>
            <p className="text-text-muted">Full legal text will be provided at production launch.</p>
          </>
        ) : (
          <>
            <p className="font-semibold text-text-primary">Dobara Privacy Policy (Demo)</p>
            <p>1. We collect your mobile number, name and addresses to provide trade-in, purchase and after-sales services.</p>
            <p>2. Device IMEIs collected during inspection are encrypted, de-duplicated and used only for pricing and listing.</p>
            <p>3. We use MSG91 to deliver OTP and transactional SMS; location (city-level) is used for same-city recommendations.</p>
            <p>4. You may request account deletion in Settings; a 30-day cooling-off period applies before permanent deletion.</p>
            <p className="text-text-muted">Full legal text will be provided at production launch.</p>
          </>
        )}
      </div>
    </Modal>
  );
}

export function Register({ phone }: { phone: string }) {
  const navigate = useNavigate();
  const [password, setPassword] = useState('');
  const [confirm, setConfirm] = useState('');
  const [agree, setAgree] = useState(false);
  const [error, setError] = useState('');
  const [docOpen, setDocOpen] = useState<'agreement' | 'privacy' | null>(null);
  const [submitting, setSubmitting] = useState(false);
  // 账号类型（APP-P0-05 v2.21）：enterprise 需选门店（必填）
  const [accountType, setAccountType] = useState<'personal' | 'enterprise'>('personal');
  const [storeQuery, setStoreQuery] = useState('');
  const [storeHits, setStoreHits] = useState<IEntStoreHit[]>([]);
  const [storeSearching, setStoreSearching] = useState(false);
  const [selectedStore, setSelectedStore] = useState<IEntStoreHit | null>(null);
  const [billingContact, setBillingContact] = useState('');

  // 门店搜索（≥2 字符触发；命中预导入档案）
  useEffect(() => {
    const q = storeQuery.trim();
    if (accountType !== 'enterprise' || q.length < 2 || (selectedStore && q === `${selectedStore.name} ${selectedStore.code}`)) {
      setStoreHits([]);
      return;
    }
    setStoreSearching(true);
    const t = setTimeout(async () => {
      try {
        const res = await fetch(`/api/ent/stores?q=${encodeURIComponent(q)}`);
        const data = await res.json();
        setStoreHits(data.stores || []);
      } catch {
        setStoreHits([]);
      } finally {
        setStoreSearching(false);
      }
    }, 300);
    return () => clearTimeout(t);
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [storeQuery, accountType]);

  const errors = password ? passwordErrors(password) : [];
  const confirmMismatch = confirm.length > 0 && password !== confirm;
  const enterpriseReady = accountType === 'personal' || selectedStore !== null;
  const canSubmit =
    password.length > 0 && errors.length === 0 && password === confirm && agree && enterpriseReady && !submitting;

  const submit = async () => {
    if (!canSubmit) return;
    setSubmitting(true);
    let entBinding: IEntBinding | undefined;
    try {
      if (accountType === 'enterprise' && selectedStore) {
        // 企业注册：创建门店绑定（06 §2.12.2 user_ent_binding）
        const res = await fetch('/api/auth/ent-register', {
          method: 'POST',
          headers: { 'Content-Type': 'application/json' },
          body: JSON.stringify({ phone, password, storeId: selectedStore.id, billingContact: billingContact || undefined }),
        });
        const data = await res.json().catch(() => ({}) as { user?: { entBinding?: IEntBinding } });
        entBinding = data.user?.entBinding;
        if (!entBinding) {
          setError('Enterprise registration failed. Please try again.');
          setSubmitting(false);
          return;
        }
      } else {
        await fetch('/api/auth/register', {
          method: 'POST',
          headers: { 'Content-Type': 'application/json' },
          body: JSON.stringify({ phone, password }),
        }).catch(() => { /* demo fallback below */ });
      }
      markRegistered(phone);
      setUser(phone, 'Demo User', entBinding);
      navigate('/home', { replace: true });
    } finally {
      setSubmitting(false);
    }
  };

  return (
    <div className="min-h-screen bg-surface flex items-center justify-center">
      <div className="w-full max-w-sm">
        <div className="text-center mb-8">
          <h1 className="text-h2 font-extrabold text-primary-500 tracking-tight">Set your password</h1>
          <p className="text-body text-text-muted mt-2">Finish creating your account for +91 {phone}</p>
        </div>

        <Card className="space-y-4" data-testid="register-card">
          <div>
            <Input
              label="Password"
              type="password"
              value={password}
              onChange={(e: ChangeEvent<HTMLInputElement>) => { setPassword(e.target.value); setError(''); }}
              placeholder="8–20 chars, 2+ character types"
              data-testid="register-password"
              error={errors[0]}
            />
            {/* Password strength indicator (APP-P0-05) */}
            {password && (
              <div className="flex items-center gap-2 mt-2" data-testid="password-strength">
                <div className="flex gap-1 flex-1">
                  {[1, 2, 3].map((i) => (
                    <div
                      key={i}
                      className={`h-1.5 flex-1 rounded-full transition-colors ${strengthOf(password).level >= i ? STRENGTH_COLORS[strengthOf(password).level] : 'bg-surface-high'}`}
                    />
                  ))}
                </div>
                <span className="text-caption text-text-muted w-14 text-right">{strengthOf(password).label}</span>
              </div>
            )}
            {errors.length > 1 && (
              <ul className="text-caption text-text-muted mt-1.5 space-y-0.5 list-disc list-inside" data-testid="password-rules">
                {errors.slice(1).map((e) => <li key={e}>{e}</li>)}
              </ul>
            )}
          </div>

          <Input
            label="Confirm Password"
            type="password"
            value={confirm}
            onChange={(e: ChangeEvent<HTMLInputElement>) => setConfirm(e.target.value)}
            placeholder="Re-enter password"
            error={confirmMismatch ? 'Passwords do not match' : undefined}
            data-testid="register-confirm"
          />

          {/* 账号类型（APP-P0-05 v2.21）：企业必填门店，绑定即 ROLE-ENT */}
          <div>
            <p className="text-caption text-text-muted mb-1 font-semibold">Account type</p>
            <div className="flex gap-2">
              {(['personal', 'enterprise'] as const).map((t) => (
                <button
                  key={t}
                  type="button"
                  data-testid={`register-type-${t}`}
                  onClick={() => { setAccountType(t); setSelectedStore(null); setStoreQuery(''); }}
                  className={`flex-1 px-3 py-2 rounded-md text-caption font-medium border transition-colors flex items-center justify-center gap-1.5 ${
                    accountType === t
                      ? 'border-primary-500 bg-primary-50 text-primary-700'
                      : 'border-border text-text-secondary hover:bg-surface-high'
                  }`}
                >
                  {t === 'enterprise' && <Building2 size={14} />}
                  {t === 'personal' ? 'Personal' : 'Enterprise'}
                </button>
              ))}
            </div>
            {accountType === 'enterprise' && (
              <div className="mt-3 space-y-2" data-testid="register-enterprise-block">
                {selectedStore ? (
                  // 选中门店：档案信息只读回显（预导入数据，不可编辑）
                  <div className="rounded-md border border-border p-3 space-y-1" data-testid="register-store-selected">
                    <div className="flex items-center justify-between">
                      <p className="text-body font-semibold text-text-primary flex items-center gap-1.5">
                        <Building2 size={14} /> {selectedStore.name}
                      </p>
                      <button
                        type="button"
                        className="text-caption text-primary-600 underline"
                        onClick={() => { setSelectedStore(null); setStoreQuery(''); }}
                      >
                        Change
                      </button>
                    </div>
                    <p className="text-caption text-text-muted">
                      Store code: {selectedStore.code || '—'} · {selectedStore.city}
                    </p>
                    <p className="text-caption text-text-muted">
                      Enterprise: {selectedStore.enterpriseName || '— (profile not filled)'}
                    </p>
                    <p className="text-caption text-text-muted">GSTIN: {selectedStore.gstin || '—'}</p>
                    <Input
                      label="Billing contact (optional)"
                      value={billingContact}
                      onChange={(e: ChangeEvent<HTMLInputElement>) => setBillingContact(e.target.value)}
                      placeholder="Name · phone (for credit settlement)"
                      data-testid="register-billing-contact"
                    />
                  </div>
                ) : (
                  <>
                    <Input
                      label="Your store (required)"
                      value={storeQuery}
                      onChange={(e: ChangeEvent<HTMLInputElement>) => setStoreQuery(e.target.value)}
                      placeholder="Search by store name or code, e.g. Andheri / ST-MH-0001"
                      data-testid="register-store-search"
                    />
                    {storeSearching && <p className="text-caption text-text-muted">Searching…</p>}
                    {storeHits.length > 0 && (
                      <div className="rounded-md border border-border divide-y divide-border" data-testid="register-store-results">
                        {storeHits.map((s) => (
                          <button
                            key={s.id}
                            type="button"
                            data-testid={`register-store-hit-${s.id}`}
                            onClick={() => { setSelectedStore(s); setStoreHits([]); }}
                            className="w-full text-left px-3 py-2 hover:bg-surface-high"
                          >
                            <p className="text-body font-medium text-text-primary">{s.name}</p>
                            <p className="text-caption text-text-muted">
                              {s.code || s.id} · {s.city}
                              {s.enterpriseName ? ` · ${s.enterpriseName}` : ''}
                            </p>
                          </button>
                        ))}
                      </div>
                    )}
                    {!storeSearching && storeQuery.trim().length >= 2 && storeHits.length === 0 && (
                      <p className="text-caption text-dobara-error">
                        No pre-imported store matches. Contact the platform admin.
                      </p>
                    )}
                  </>
                )}
              </div>
            )}
          </div>

          <label className="flex items-start gap-2 text-caption text-text-secondary cursor-pointer" data-testid="register-agree">
            <input
              type="checkbox"
              checked={agree}
              onChange={(e) => setAgree(e.target.checked)}
              className="accent-primary-500 w-4 h-4 mt-0.5 shrink-0"
            />
            <span>
              I have read and agree to the{' '}
              <button type="button" className="text-primary-600 underline" onClick={() => setDocOpen('agreement')}>
                User Agreement
              </button>{' '}
              and{' '}
              <button type="button" className="text-primary-600 underline" onClick={() => setDocOpen('privacy')}>
                Privacy Policy
              </button>
              .
            </span>
          </label>

          {error && <p className="text-caption text-dobara-error" data-testid="register-error">{error}</p>}

          <Button
            onClick={submit}
            loading={submitting}
            disabled={!canSubmit}
            className="w-full"
            data-testid="complete-registration"
          >
            Complete Registration
          </Button>
          {!agree && (
            <p className="text-caption text-text-muted text-center">Agree to the terms to enable registration</p>
          )}
          {accountType === 'enterprise' && !selectedStore && (
            <p className="text-caption text-text-muted text-center" data-testid="register-store-required-hint">
              Enterprise accounts must select a store to complete registration
            </p>
          )}
        </Card>

        <LegalDoc doc={docOpen} open={docOpen !== null} onClose={() => setDocOpen(null)} />
      </div>
    </div>
  );
}
